version: '3.8'

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - auth-db

  auth-db:
    image: postgres:15
    container_name: auth-db
    restart: always
    environment:
      POSTGRES_DB: micro-auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - auth-data:/var/lib/postgresql/data

volumes:
  auth-data:
